name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.20.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63c09bc7aa43058cf906138414e2db06d3cc372522186cfc74e1d2ee7d5a48b8"

[versions]
fabric = "0.19.2"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.6"]
