name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.20.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bd6788ab9458395e8a0c91b2a6ea9df74191a9a12b872f59c9d030be0d3513d"

[versions]
fabric = "0.18.4"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.6"]
