name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.20.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b1a7b383c1d97428d8dacc68408dd3846975e63a61d29ce80c8131af0d83a1"

[versions]
fabric = "0.18.4"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.6"]
