name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f66a27f83cf54b8363514ac6ef2fcb1e0ca1713ca95b0d1e483ed68370fe1296"

[versions]
fabric = "0.18.4"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.2"]
