name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b789210d27dc443dada3e007623485992abf28d537489bac59088339f86791b"

[versions]
fabric = "0.18.4"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.2"]
