name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28166ba97f36cc4904eb4fcedd39e287bad44e43f69b78a61c35c746826227f8"

[versions]
fabric = "0.18.4"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.2"]
