name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a5b1a3bb9287f648c36314440ee3818eef22a1836fd93dae34bc51517bb46de"

[versions]
fabric = "0.19.2"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
