name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dfc87a922c9db8e8ac175978c379109b78df9c9e25a28eecd2a17a3eb6c5b92"

[versions]
fabric = "0.19.2"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
