name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "114238adfa1fd38bc28e9c99c1934f5ad7794c495bdc327be706ec18b4c1b38d"

[versions]
fabric = "0.19.2"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
