name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d376e44e96bdd99915293b150a2570d7b45962c3eb0e7dfc64d75449690b4550"

[versions]
fabric = "0.19.2"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
