name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "577937e7c662ab40db00f8efd3b5f88d1f08a4b146bdc5c17236b6fd2b3aa03d"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
