name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f1495ffa4d13d0f054c91c4dc87e188533fac69edb8c5e43a2a9e428f436693"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
