name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6b3a96bfe36603890bd97cd05c8bb3553b6b119b89a072f75aa7c80ac3eadef"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11"]
