name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca86a5440b904a7e0009b9e6c10eee5961fa69382dac0d975fc1e1941a523380"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11"]
