name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f860ad89b8a06282336e71046ae23a1b9fe2407ae36124e00b4adaef17284dd4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11"]
