name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b5572e9e68ca278b78865dfd2ad7b8e76508dfe5722795079259121f1b54d7a"

[versions]
fabric = "0.18.4"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
