name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04f2ed3351d84e5e4f043a19deafa67b183f6de60e3ec83c3e23fc4ed67a6ecb"

[versions]
fabric = "0.18.4"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
