name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "26.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78fd1489b3ef4272208e507055eb0b40f79fc3d7fc4a88621e52f90e6671ebea"

[versions]
fabric = "0.18.4"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
